export type CreditsMoteDataPointer = `data/${CreditsMotePointer}`;
export type CreditsMotePointer = ``
  | `name`
  | `sections/${string}/element/entries/${string}/element/name/name`
  | `sections/${string}/element/entries/${string}/element/name/use_cjk`
  | `sections/${string}/element/entries/${string}/element/name`
  | `sections/${string}/element/entries/${string}/element/names/${string}/element/name`
  | `sections/${string}/element/entries/${string}/element/names/${string}/element/use_cjk`
  | `sections/${string}/element/entries/${string}/element/names/${string}/element`
  | `sections/${string}/element/entries/${string}/element/names/${string}/order`
  | `sections/${string}/element/entries/${string}/element/names/${string}`
  | `sections/${string}/element/entries/${string}/element/names`
  | `sections/${string}/element/entries/${string}/element/role/skip`
  | `sections/${string}/element/entries/${string}/element/role/text`
  | `sections/${string}/element/entries/${string}/element/role`
  | `sections/${string}/element/entries/${string}/element/type`
  | `sections/${string}/element/entries/${string}/element`
  | `sections/${string}/element/entries/${string}/order`
  | `sections/${string}/element/entries/${string}`
  | `sections/${string}/element/entries`
  | `sections/${string}/element/group_color/b`
  | `sections/${string}/element/group_color/g`
  | `sections/${string}/element/group_color/r`
  | `sections/${string}/element/group_color`
  | `sections/${string}/element/name/skip`
  | `sections/${string}/element/name/text`
  | `sections/${string}/element/name`
  | `sections/${string}/element/subtext/skip`
  | `sections/${string}/element/subtext/text`
  | `sections/${string}/element/subtext`
  | `sections/${string}/element`
  | `sections/${string}/order`
  | `sections/${string}`
  | `sections`
  | `wip/notes/${string}/element/author`
  | `wip/notes/${string}/element/text`
  | `wip/notes/${string}/element/timestamp`
  | `wip/notes/${string}/element`
  | `wip/notes/${string}/order`
  | `wip/notes/${string}`
  | `wip/notes`
  | `wip/staging`
  | `wip`;
