// Generated by ts-to-zod
import { z } from 'zod';
import { yyBaseSchema } from './YyBase.js';

export type YyScript = z.infer<typeof yyScriptSchema>;
export const yyScriptSchema = yyBaseSchema.extend({
  isDnD: z.boolean().default(false),
  isCompatibility: z.boolean().default(false),
  resourceType: z.literal('GMScript').default('GMScript'),
});
