// Generated by ts-to-zod
import { z } from 'zod';
import { configValuesSchema, yyBaseSchema, yyParentSchema } from './YyBase.js';
import { fixedNumber, unstable } from './utility.js';

export enum SoundBitDepth {
  Bit8,
  Bit16,
}
export enum SoundChannel {
  Mono,
  Stereo,
  ThreeD,
}

export enum SoundCompression {
  Uncompressed,
  Compressed,
  UncompressedOnLoad,
  CompressedStreamed,
}

const soundChannelSchema = z.nativeEnum(SoundChannel);

const soundCompressionSchema = z.nativeEnum(SoundCompression);

const soundBitDepthSchema = z.nativeEnum(SoundBitDepth);

export type SoundChannelAsString = keyof typeof SoundChannel;
export type SoundCompressionAsString = keyof typeof SoundCompression;

export type SoundSampleRate = z.infer<typeof soundSampleRateSchema>;
const soundSampleRateSchema = z.union([
  z.literal(5512),
  z.literal(11025),
  z.literal(22050),
  z.literal(32000),
  z.literal(44100),
  z.literal(48000),
]);

const audioGroupIdSchema = z
  .object({
    name: z.string(),
    path: z.string(),
  })
  .default({
    name: 'audiogroup_default',
    path: 'audiogroups/audiogroup_default',
  });

export type YySoundLegacy = z.infer<typeof yySoundSchemaLegacy>;
export const yySoundSchemaLegacy = yyBaseSchema.extend({
  compression: soundCompressionSchema.default(0),
  conversionMode: z.number().optional().default(0),
  volume: fixedNumber(z.number().min(0).max(1)).default(1),
  preload: z.boolean().default(false),
  bitRate: z.number().default(128),
  sampleRate: soundSampleRateSchema.default(44100),
  type: soundChannelSchema.default(1),
  bitDepth: soundBitDepthSchema.default(1),
  audioGroupId: audioGroupIdSchema,
  /** `${name}.${ext} (e.g. mySound) */
  soundFile: z.string(),
  /**
   * Duration of the sound. Automatically
   * computed by GameMaker, so Stitch can generally
   * ignore it.
   */
  duration: fixedNumber(z.number(), 2).optional(),
  resourceType: z.literal('GMSound').default('GMSound'),
  resourceVersion: z.literal('1.0').default('1.0'),
});

export type YySoundV1 = z.infer<typeof yySoundSchemaV1>;
export const yySoundSchemaV1 = unstable({
  $GMSound: z.literal(''),
  '%Name': z.string(),
  audioGroupId: audioGroupIdSchema,
  bitDepth: soundBitDepthSchema.default(1),
  bitRate: z.number().default(128),
  compression: soundCompressionSchema.default(0),
  conversionMode: z.number().optional().default(0),
  /**
   * Duration of the sound. Automatically
   * computed by GameMaker, so Stitch can generally
   * ignore it.
   */
  duration: fixedNumber(z.number(), 2).optional(),
  name: z.string(),
  parent: yyParentSchema,
  preload: z.boolean().default(false),
  resourceType: z.literal('GMSound').default('GMSound'),
  resourceVersion: z.literal('2.0').default('2.0'),
  sampleRate: soundSampleRateSchema.default(44100),
  soundFile: z.string(),
  type: soundChannelSchema.default(1),
  volume: fixedNumber(z.number().min(0).max(1)).default(1),
});

export type YySoundV2 = z.infer<typeof yySoundSchemaV2>;
export const yySoundSchemaV2 = unstable({
  $GMSound: z.literal('v2'),
  '%Name': z.string(),
  audioGroupId: audioGroupIdSchema,
  bitDepth: soundBitDepthSchema.default(1),
  channelFormat: z.number().default(0),
  compression: soundCompressionSchema.default(0),
  compressionQuality: z.number().default(4),
  ConfigValues: configValuesSchema,
  conversionMode: z.number().optional().default(0),
  duration: fixedNumber(z.number(), 2).optional(),
  exportDir: z.string().default(''),
  name: z.string(),
  parent: yyParentSchema,
  preload: z.boolean().default(false),
  resourceType: z.literal('GMSound').default('GMSound'),
  resourceVersion: z.literal('2.0').default('2.0'),
  sampleRate: soundSampleRateSchema.default(44100),
  soundFile: z.string(),
  volume: fixedNumber(z.number().min(0).max(1)).default(1),
});

export type YySound = YySoundLegacy | YySoundV1 | YySoundV2;
export const yySoundSchema = z.discriminatedUnion('resourceVersion', [
  yySoundSchemaLegacy,
  z.discriminatedUnion('$GMSound', [yySoundSchemaV1, yySoundSchemaV2]),
]);
